### ISSUE TITLE
import_from_file destination formatting

### ISSUE THREAD

**Issue by mplunney** [badoo/pyexasol#18]
Hello, I am working on an ETL process to import csv and xlsx data into our Exasol data warehouse. I am able to successfully load the data using pyexasol, but I'm having trouble attempting to get it into a destination table that is not all caps (our database nomenclature uses camel case). 

I have tried the `quote_ident` function, but it returns the same `Value ["TestTable"] is not a safe identifier` exception that just passing `'"TestTable"'` as the destination table argument to the `import_from_file` function does.

Am I misunderstanding the purpose of this function? Or am I not using it properly? I've been through all of the documentation, but haven't found a way to import with this package to a destination with lower case characters in the string.

```
cnxn.import_from_file(open(importFile, 'rb'), '"TestTable"')
```
```
dest = pyexasol.ExaFormatter.quote_ident('TestTable')
cnxn.import_from_file(open(importFile, 'rb'), dest)
```

Many thanks for any advice you can give.

**Comment by wildraid** [comment]
Hello,

It's an interesting point. Initial driver was implemented with `.quote_ident()` approach instead of current `.safe_ident()`. So table name `users` was translated into `IMPORT ... INTO "users"`.

However, it caused a lot of confusion and multiple requests to switch it to more straightforward behavior with `users` being translated as just `IMPORT ... INTO users` without extra quotes and keeping the original Exasol logic of automatic uppercasing of identifiers.

It is generally a good practice to keep database objects without quotes. It you still have a chance, I suggest to rename everything and save energy in future.

Anyway, I agree that it should be possible to use camel-case identifiers with HTTP transport functions. I'll introduce a connection option to enable strict identifier treatment in the next version. It should be available tomorrow.

Hope it helps!

**Comment by mplunney** [comment]
Hey, awesome! Thanks for the quick reply, and I'll keep my eye out for the update.

**Comment by wildraid** [comment]
Please update to 0.5.3, add connection option `quote_ident=True` and try again. All identifiers passed to EXPORT \ IMPORT functions should be quoted and escaped.

`pip install --upgrade pyexasol`

```
C = pyexasol.connect(..., quote_ident=True)
pd = C.export_to_pandas('camelCaseTableName!')
```

Query formatting converters remain the same: `!i` for "safe identifiers" without quotes and `!q` for quoted and escaped identifiers.

Please let me know if it works for you.

**Comment by wildraid** [comment]
If someone finds this issue later wandering why this is not the default behavior. It's very to explain.

Please consider following example:
```python
# Unquoted identifiers are automatically converted to upper case by Exasol
C.export_to_pandas('SELECT * FROM my_little_table')

# This works by default, but it will break with quote_ident=True, since real table name in MY_LITTLE_TABLE
C.export_to_pandas('my_little_table')
```

We assume that overwhelming majority of Exasol customers will stay with default automatic upper case naming. So identifiers passed to helper functions follow this notation and are not escpaed by default for convenience.

**Comment by mplunney** [comment]
Works like a charm! Greatly appreciate your assistance, and thanks for creating this module.
