### ISSUE TITLE
Undetermined behavior of SCRIPT_OUTPUT

### ISSUE THREAD

**Issue by LennartAtExasol** [badoo/pyexasol#42]
The following Python3 UDF script looks for the shortest string in a given input set.

```
CREATE OR REPLACE PYTHON3 SET SCRIPT shortest_string(input_string VARCHAR(2000000)) RETURNS VARCHAR(2000000) AS 
def run(ctx):
 short = ""
 l = 2e6
 
 print('outer')
 while True:
  _l = len(ctx.input_string)
  print('inner')
  if _l < l:
        l = _l
        short = ctx.input_string
        print('if_inner')
  
  if not ctx.next(): break
 return short
/
```

When pyexasols script_output is listening it prints:
```
1 * 'outer'
x * 'inner'
y < x * 'if_inner'
```

Where x depends on the number of rows in the set as it should be.

However if "print('inner')" is commented out **nothing** is printed at all to the listener. Neither 'outer' nor 'if_inner'. I can't explain this behaviour.

**Comment by LennartAtExasol** [comment]
I just found out, that `print('outer', flush=True)` solves the issue.
Flushing should be handled by pyexasol. Or this behaviour should be documented if intended.

**Comment by wildraid** [comment]
I guess, buffered output for STDOUT / STDERR is a general Python thing. Data does not leave the Python process, so nothing is being sent to script output server.

Please note that debug request handler currently flushes after every single line: https://github.com/badoo/pyexasol/blob/d111f951974c8d6f4d8594db1b423336da459295/pyexasol/script_output.py#L153

**Comment by wildraid** [comment]
In theory, you should be getting the output as soon as SQL statement execution is finished and Python VM's are terminated. And this problem should affect long running queries only.

Is that correct?

**Comment by LennartAtExasol** [comment]
Actually I encountered the problem on 40row table. My guess is that the buffer never got full and so was never pushed out. Flushing in the run() method solves the issue. So its pushed out for every input set.

**Comment by wildraid** [comment]
It might be worth checking how Python 3 VM's are currently handled by Exasol UDF client. Maybe it's worth adding explicit `.flush()` for STDOUT / STDERR after every call of `run()` function.

Also, I think Python may not have a chance to terminate properly and do all the "finishing actions" due to SWIG <-> Python interactions.

**Comment by wildraid** [comment]
Could you also try to run the same 40 rows query with `.execute_udf_output()` instead of debug mode? https://github.com/badoo/pyexasol/blob/master/docs/REFERENCE.md#execute_udf_output

It uses slightly different method of reading data and it should save all the output into files. Let's see if it's going to miss those lines or not.

Please set `udf_output_dir` connection option to make those files permanent, not the tmp-files.

Thank you.

**Comment by wildraid** [comment]
@LennartAtExasol 

I did some tests. Yes, it is purely the "output buffering" problem. All other parts, including PyEXASOL script output server, are working as intended. Output is simply not sent from VM's.

I've added an extra line to documentation mentioning the necessity of flushing while working with debug mode. `.execute_udf_output()` (normal mode) function is not affected since it returns only when SQL query is finished and all VM's outputs are flushed.

Please let me know if you think this logic can be improved even further. And thank you for raising this issue.

**Comment by LennartAtExasol** [comment]
@wildraid 
thanks for taking care!

I think it's important to document this behaviour so people don't have to explore the behaviour like I did. Apart from documenting the behaviour I do not think that there is more to do for now. If I come up with an improvement I'll let you know. For now this issue is resolved. Thanks!
