### ISSUE TITLE
pyexasol not recording logout_time in exa_dba_audit_sessions

### ISSUE THREAD

**Issue by ralphielauren** [badoo/pyexasol#52]
- pyexasol version 0.12.1 or 0.10.1
- python 3.7

**Closing a connection in a python script, doesn't show logout_time in exasol metadata table.**

To reproduce:

1. open an exasol connection
2. run a dummy query
3. close connection
4. try to run the query again

```python
>>> import os
>>> import pyexasol
>>> C = pyexasol.connect(dsn=os.getenv("EXASOL_DSN"), user=os.getenv("EXASOL_USR"), password=os.getenv("EXASOL_PWD"))
>>> stmt = C.execute("/* test */ SELECT 1;")
>>> print(stmt)
<ExaStatement session_id=1667199361071797309 stmt_idx=1>
>>> C.close()
>>> C.execute("/* test */ SELECT 1;")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/uid/.virtualenvs/test/lib/python3.7/site-packages/pyexasol/connection.py", line 179, in execute
    return self.cls_statement(self, query, query_params)
  File "/Users/uid/.virtualenvs/test/lib/python3.7/site-packages/pyexasol/statement.py", line 36, in __init__
    raise ExaRuntimeError(self.connection, "Exasol connection was closed")
```

However when I checked the **exa_statistics.exa_dba_audit_sessions** table, no logout time was recorded:

```sql
SELECT 
  session_id,
  login_time,
  logout_time,
  user_name,
  client,
  driver,
  os_name
FROM exa_statistics.exa_dba_audit_sessions 
WHERE session_id = '1667835135723529859';
```

Even the next day (accounting for some delays) the logout time was 2 hours later.

Am I missing something?

**Comment by wildraid** [comment]
Hello.

Could you please try adding the following command before `C.close()` and see if it helps with logout time logging:

```
C.req({
    'command': 'disconnect'
})
```

At this moment PyEXASOL does not call the "disconnect" command explicitly due to performance considerations. Also, it is not guaranteed that connection is still opened and fully operational during the destruction of `ExaConnection` object, so the explicit "disconnect" call might produce error during garbage collection.

PyEXASOL does send a simple frame with `OPCODE_CLOSE` followed by `socket.shutdown()` instead, which is in line with WebSocket protocol standards. It is much faster, and it does not produce errors in case of failure.

I've discussed it with Exasol support and received a following response on 4th of Feb 2020:

> We've discussed the suggestion of implicitly calling disconnect when receiving CLOSE, and we think we can do that in a future version. I will inform you as soon as the roadmap ticket for this second issue is created.
> 
> Thanks for the information and suggestion!

So this behaviour should improve automatically in future versions. And it should not cause any problems with current versions, outside of `LOGOUT_TIME` logging. The lingering sessions should not consume any extra resources.

Hope it helps!

**Comment by wildraid** [comment]
In theory, we can add the parameter `disconnect=True/False` for `.close()` method with `False` as default.

Just for people who still need the `disconnect` call purely for housekeeping reasons and do not mind the extra API call.

**Comment by wildraid** [comment]
Ok, I did some testing and noticed that explicit `disconnect` call definitely helps with logout time. I've also noticed that this problem is also true for other types of connections (e.g. JDBC / ODBC), which may not always close the connection properly.

I'll consider adding explicit `disconnect` call in `.close()` function regardless of performance impact. And I'll keep track on Exasol updates to remove it when new version with improved OP_CLOSE treatment becomes available.

Thank you for pointing this out.

**Comment by wildraid** [comment]
@ralphielauren , please update to version `0.13.0` and check the `logout_time` afterwards.

Command `disconnect` will be sent to Exasol server automatically during `.close()`.

For people who might find this ticket later while trying to debug problems with `disconnect`, you may switch back to original behaviour using `.close(disconnect=False)`.

I'll consider removing this extra `disconnect` call when Exasol actually implements the proper handling of OPCODE_CLOSE frame on server side.

**Comment by ralphielauren** [comment]
Hey, will try this and get back to you on Monday. 

Thanks for fixing!

**Comment by ralphielauren** [comment]
@wildraid confirmed it works with 0.13.0. Thank you for addressing this
