### ISSUE TITLE
Do you plan to support REJECT LIMIT option to import? 

### ISSUE THREAD

**Issue by cedorbelgorod** [badoo/pyexasol#76]
When importing, you can specify the allowed number of bad lines, whether this parameter will be supported during import.

**Comment by wildraid** [comment]
No plans to add it right now, since this parameter makes more harm than good - it hides errors and various problems with data. Also, getting faulty rows back from server is a bit complicated and requires a reader process which will not block.

In most cases, it's much better to fix the data source or add a proper external data validation, which is not related to Exasol.
